### ISSUE TITLE
could not make due to the make error "make: *** No rule to make target 'obj/fpm.pb.cc', needed by 'fibmgr'.  Stop."

### ISSUE THREAD

**Issue by soukichi** [zstas/fpm_vpp#1]
Hello,

I got a error message when I try to make: "make: *** No rule to make target 'obj/fpm.pb.cc', needed by 'fibmgr'.  Stop." .
Could you help me to solve it?

terminal logs below:
`# make`
g++ -c -g -Wall -std=c++17 -Isrc/ src/netlink.cpp -o obj/netlink.o
src/netlink.cpp: In static member function ‘static int Netlink::data_cb_route(const nlmsghdr*, void*)’:
src/netlink.cpp:4:19: warning: unused variable ‘rm’ [-Wunused-variable]
    4 |     struct rtmsg *rm = reinterpret_cast<struct rtmsg *>( mnl_nlmsg_get_payload( nlh ) );
      |                   ^~
src/netlink.cpp: In member function ‘void Netlink::process(std::vector<unsigned char>&)’:
src/netlink.cpp:46:9: warning: unused variable ‘ret’ [-Wunused-variable]
   46 |     int ret;
      |         ^~~
g++ -c -g -Wall -std=c++17 -Isrc/ src/main.cpp -o obj/main.o
make: *** No rule to make target 'obj/fpm.pb.cc', needed by 'fibmgr'.  Stop.

**Comment by zstas** [comment]
Hello,

I've just sent a fix (pretty dumb, but it compiles now). Please tell me if you'll met any new issues.

**Comment by soukichi** [comment]
Hello,

Thank you for update.
However, it still saying same error as below.

`# make`
`make: *** No rule to make target 'obj/fpm.pb.cc', needed by 'fibmgr'.  Stop.`
`#`

When I changed one line, and make obj dir, suceeded it!
Thank you so much your help.

```
- SRC_GEN = $(wildcard $(SRCDIR)/fpm/*.cc $(SRCDIR)/qpb/*.cc) OBJ_GEN =  $(addprefix $(OBJDIR)/,$(notdir $(SRC_GEN:.cpp=.o)))
+ SRC_GEN = $(wildcard $(SRCDIR)/fpm/*.cc $(SRCDIR)/qpb/*.cc) OBJ_GEN =  $(addprefix $(OBJDIR)/,$(notdir $(SRC_GEN:.cc=.o))) 
```
